
\documentclass[10pt]{article}
%\VignetteDepends{knitr}
%\VignetteIndexEntry{CellMix-unitTests}
%\VignetteCompiler{knitr}
%\VignetteEngine{knitr::knitr}
\usepackage{vmargin}
\setmargrb{0.75in}{0.75in}{0.75in}{0.75in}

<<setup, include=FALSE>>=
pkg <- 'CellMix'
require( pkg, character.only=TRUE )
prettyVersion <- packageDescription(pkg)$Version
prettyDate <- format(Sys.Date(), '%B %e, %Y')
authors <- packageDescription(pkg)$Author
@

\usepackage[colorlinks]{hyperref}
\author{\Sexpr{authors}}
\title{\texttt{\Sexpr{pkg}}: Unit testing results\footnote{Vignette computed  on Tue Jun  4 18:14:22 2013}}
\date{\texttt{\Sexpr{pkg}} version \Sexpr{prettyVersion} as of \Sexpr{prettyDate}}
\begin{document}
\maketitle

\section{Details}
\begin{verbatim}

RUNIT TEST PROTOCOL -- Tue Jun  4 18:14:21 2013 
*********************************************** 
Number of test functions: 25 
Number of deactivated test functions: 1 
Number of errors: 0 
Number of failures: 0 

 
1 Test Suite : 
package:CellMix - 25 test functions, 0 errors, 0 failures



Details 
*************************** 
Test Suite: package:CellMix 
Test function regexp: ^test. 
Test file regexp: ^runit.*.[rR]$ 
Involved directory: 
/tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests 
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.algorithms.R 
test.all: (10 checks) ... OK (11.06 seconds)
test.autoselect : DEACTIVATED, Unit test for DSection skipped due to error with io package
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.data.R 
test.Abbas: (1 checks) ... OK (0.01 seconds)
test.GSE11057: (14 checks) ... OK (6.7 seconds)
test.GSE11058: (15 checks) ... OK (3.24 seconds)
test.GSE19830: (12 checks) ... OK (2.59 seconds)
test.GSE20300: (12 checks) ... OK (1.95 seconds)
test.GSE22886.A: (7 checks) ... OK (2.77 seconds)
test.GSE22886.B: (7 checks) ... OK (1.57 seconds)
test.GSE24223: (11 checks) ... OK (5.46 seconds)
test.GSE29832: (11 checks) ... OK (1.54 seconds)
test.GSE33076: (13 checks) ... OK (1.49 seconds)
test.GSE3649: (7 checks) ... OK (1.76 seconds)
test.GSE5350: (14 checks) ... OK (3.49 seconds)
test.HaemAtlas: (9 checks) ... OK (1.76 seconds)
test.SLE: (4 checks) ... OK (0.01 seconds)
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.datasource.R 
test.DataSource: (20 checks) ... OK (0.38 seconds)
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.idtype.R 
test.asGeneIdentifierType: (49 checks) ... OK (0.16 seconds)
test.idtype: (9 checks) ... OK (8.48 seconds)
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.markers.R 
test.brackets: (0 checks) ... OK (0.01 seconds)
test.MarkerList: (5 checks) ... OK (0.02 seconds)
test.rmarkers: (20 checks) ... OK (0.01 seconds)
test.stack: (16 checks) ... OK (0.03 seconds)
test.subset: (4 checks) ... OK (0.04 seconds)
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.registry-markers.R 
test.load: (9 checks) ... OK (1.36 seconds)
--------------------------- 
Test file: /tmp/Rpkglib_74da3f03e4ac/CellMix/unitTests/runit.stats.R 
test.applyBy: (42 checks) ... OK (0.29 seconds)

Total execution time
***************************
   user  system elapsed 
 63.980   3.696  67.922 

\end{verbatim}

\section*{Session Information}
\begin{itemize}\raggedright
  \item R version 3.0.1 (2013-05-16), \verb|i686-pc-linux-gnu|
  \item Locale: \verb|LC_CTYPE=en_US.UTF-8|, \verb|LC_NUMERIC=C|, \verb|LC_TIME=en_US.UTF-8|, \verb|LC_COLLATE=en_US.UTF-8|, \verb|LC_MONETARY=en_US.UTF-8|, \verb|LC_MESSAGES=en_US.UTF-8|, \verb|LC_PAPER=C|, \verb|LC_NAME=C|, \verb|LC_ADDRESS=C|, \verb|LC_TELEPHONE=C|, \verb|LC_MEASUREMENT=en_US.UTF-8|, \verb|LC_IDENTIFICATION=C|
  \item Base packages: base, compiler, datasets, graphics, grDevices,
    grid, methods, parallel, stats, utils
  \item Other packages: annotate~1.38.0, AnnotationDbi~1.22.5,
    BH~1.51.0-1, bigmemory~4.4.3, bigmemory.sri~0.1.2, Biobase~2.20.0,
    BiocGenerics~0.6.0, CellMix~1.6, corpcor~1.6.6, csSAM~1.2.4,
    DBI~0.2-7, digest~0.6.3, graph~1.38.1, GSEABase~1.22.0,
    illuminaHumanv2.db~1.18.0, limSolve~1.5.4, NMF~0.16.2,
    org.Hs.eg.db~2.9.0, pkgmaker~0.16.4, Rcpp~0.10.3, RcppOctave~0.9.1,
    registry~0.2, rngtools~1.2, RSQLite~0.11.4, RUnit~0.4.26,
    stringr~0.6.2, synchronicity~1.1.0
  \item Loaded via a namespace (and not attached):
    AnnotationForge~1.2.1, beeswarm~0.1.5, bibtex~0.3-5,
    BiocInstaller~1.10.1, codetools~0.2-8, colorspace~1.2-2,
    dichromat~2.0-0, doParallel~1.0.1, foreach~1.4.0,
    genefilter~1.42.0, ggplot2~0.9.3.1, gridBase~0.4-6, gtable~0.1.2,
    gtools~2.7.1, IRanges~1.18.1, iterators~1.0.6, labeling~0.1,
    lpSolve~5.6.7, MASS~7.3-26, matrixStats~0.8.1, munsell~0.4,
    plyr~1.8, preprocessCore~1.22.0, proto~0.3-10, quadprog~1.5-5,
    RColorBrewer~1.0-5, reshape2~1.2.2, R.methodsS3~1.4.2,
    scales~0.2.3, splines~3.0.1, stats4~3.0.1, survival~2.37-4,
    tools~3.0.1, XML~3.96-1.1, xtable~1.7-1
\end{itemize}

\end{document}

